name: My-GitHubActions-Basics

env:
    APPLICATION_NAME: "MyApp"
on:
    push: 
        branches: 
            - main
 
jobs:
    my-testing:
        runs-on: ubuntu-latest
        
        steps:
        - name: Print Hello Message from my-testing
          run : echo "Hello world from my-testing"

    my-deploy:
        runs-on: ubuntu-latest
        needs: my-testing

        steps:
        - name: Print Hello message from my-deploy
          run : |
            echo "Hello world from my-deploy"
            echo value of env var is: ${{ env.APPLICATION_NAME}}
          
