name: Context testing
env:
    ENV_VAR: "Value-of-env-var"
on: push
jobs:
    dump_context_to_log:
        env:
          JOB_ENV_VAR: "Value-of-job-env-var"
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env : 
                GITHUB_CONTEXT: ${{ toJson(github) }}
                COMMITER: ${{ github.event.commits[0].author.name }}
                #URL: ${{ github.event.commits[0].Url}}
              run : |
                echo "$GITHUB_CONTEXT"  
                echo "Commiter is - $COMMITER"
                echo "Url is -- ${{ github.event.commits[0].Url }}"
                echo "Runner OS is - ${{ runner.os }}"
