name: CI
on: push
jobs:
    my-check:
        if: ${{ github.ref == 'refs/heads/main' }}
        runs-on: ubuntu-latest
        steps:
            - name: Init step
              run : echo "Running on branch $GITHUB_REF"


