name: Context testing
env:
    ENV_VAR: "Value-of-env-var"
on: push
jobs:
    dump_context_to_log:
        env:
          JOB_ENV_VAR: "Value-of-job-env-var"
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env : 
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run : echo "$GITHUB_CONTEXT"  

            - name: Dump job context
              env : 
                JOB_CONTEXT: ${{ toJson(job)}}
              run : echo "$JOB_CONTEXT"  

            - name: Dump steps context
              env : 
                STEPS_CONTEXT: ${{ toJson(steps) }}
              run : echo "$STEPS_CONTEXT"    

            - name: Dump runner context
              env:
                RUNNER_CONTEXT: ${{ toJson(runner) }}
              run : |
                echo "$RUNNER_CONTEXT"    
                echo "Runner os is: $RUNNER_OS"
                echo "Runner arch is: $RUNNER_ARCH"
                echo "Runner ws is: $RUNNER_WORKSPACE"
            - name: Dump env context
              env : 
                ENV_CONTEXT: ${{ toJson(env) }}    
              run: echo "$ENV_CONTEXT"  
            - name: Dump strategy context
              env : 
                NEEDS: ${{ toJson(needs) }}
              run : echo "Strategy context is $NEEDS"     

    second_job:
        runs-on: ubuntu-latest
        needs: dump_context_to_log
        steps:
            - name: Init step in second-job
              run : echo Hello from Second-job                        