name: Context testing
env:
    ENV_VAR: "Value-of-env-var"
on: push
jobs:
    dump_context_to_log:
        env:
          JOB_ENV_VAR: "Value-of-job-env-var"
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env : 
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run : |
                echo "$GITHUB_CONTEXT"  
                echo "Repo is - $GITHUB_EVENT.AFTER"
