name: My-GitHub-Actions

on:
    push:
        branches: [main]

jobs:
    my-testing:
        runs-on: ubuntu-latest

        steps:
            - name: View current folder
              run : ls -la
